In [1]:
import torch
import numpy as np

In [3]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data


tensor([[1, 2],
        [3, 4]])

In [10]:
np_array = np.array(data)
x_data1 = torch.from_numpy(np_array)
x_data1

tensor([[1, 2],
        [3, 4]])

In [25]:
x_ones = torch.ones_like(x_data1)
print(x_ones)
x_rand = torch.rand_like(x_data, dtype = torch.float)
x_rand

tensor([[1, 1],
        [1, 1]])


tensor([[0.7527, 0.9242],
        [0.5146, 0.7401]])

In [30]:
shape = (2,2,)
rand_tensor = torch.ones(shape)
print(rand_tensor)

tensor([[1., 1.],
        [1., 1.]])


In [42]:
x_ones.device

device(type='cuda', index=0)

In [43]:
x_ones = x_ones.to('cuda')
x_ones

tensor([[1, 1],
        [1, 1]], device='cuda:0')

In [88]:
tensor = torch.ones(5,5)
#tensor[3, 4] = 5
tensor[:,-1]

tensor([1., 1., 1., 1., 1.])

In [76]:
t1 = torch.cat([tensor, tensor] ,dim =1)
print(t1)


tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 5., 1., 1., 1., 1., 5.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


In [82]:
y1 = tensor@tensor.T
y1

tensor([[ 5.,  5.,  5.,  9.,  5.],
        [ 5.,  5.,  5.,  9.,  5.],
        [ 5.,  5.,  5.,  9.,  5.],
        [ 9.,  9.,  9., 29.,  9.],
        [ 5.,  5.,  5.,  9.,  5.]])

In [81]:
y2= torch.matmul(tensor,tensor.T)
y2

tensor([[ 5.,  5.,  5.,  9.,  5.],
        [ 5.,  5.,  5.,  9.,  5.],
        [ 5.,  5.,  5.,  9.,  5.],
        [ 9.,  9.,  9., 29.,  9.],
        [ 5.,  5.,  5.,  9.,  5.]])

In [84]:
z1= tensor.mul(tensor)
z1

tensor([[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1., 25.],
        [ 1.,  1.,  1.,  1.,  1.]])

In [99]:
agg = tensor[:,0]
print(agg)
agg.dtype
agg_item = agg.tolist()
agg_item

tensor([1., 1., 1., 1., 1.])


[1.0, 1.0, 1.0, 1.0, 1.0]

In [108]:
tensor.t_()
tensor

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [126]:
t= torch.ones(4)
n = t.numpy()
t.add_(2)
np.add(n, 1, out = n) #This change will also reflect in tensor
print(t,'\n')
print(n)
# change in tensor reflects in numpy array and vice versa. see examples below

n1 =np.ones(4)
t1= torch.from_numpy(n1) # this change will also reflect in numpy
np.add(n1, 1, out = n1)
print(t1,'\n')
print(n1)

tensor([4., 4., 4., 4.]) 

[4. 4. 4. 4.]
tensor([2., 2., 2., 2.], dtype=torch.float64) 

[2. 2. 2. 2.]
